#!/bin/bash

#### Path variables ####
dotfiles_dir=~/.dotfiles
old_dotfiles_dir=~/.dotfiles_old
dotfiles_path="dotfiles/"
dotfiles=`ls $dotfiles_path`


#### Colors ####
reset=$(tput sgr0);
red=$(tput setaf 124);



#Create directory for old dotfiles
echo -n "Creating ${red}$old_dotfiles_dir${reset} for backup of any existing dotfiles in ~"
mkdir -p $old_dotfiles_dir
echo "...done"

#Create directory for dotfiles
echo -n "Creating ${red}$dotfiles_dir${reset} for dotfiles"
mkdir -p $dotfiles_dir
echo "...done"

#Move existing dotfiles to dotfiles_old directory
echo "Moving existing dotfiles to ${red}$old_dotfiles_dir${reset}"
for file in $dotfiles; 
	do
		if [ ! -e ~/.$file ]; then
			echo "File ${red}$file${reset} won't be backuped because it doesn't exist"
		else
			echo -n "Backup ${red}$file${reset} dotfile"
			mv ~/.$file $old_dotfiles_dir
			echo "...done"
		fi
	done


#Move new dotfiles to dotfiles directory
for file in $dotfiles
	do	
		echo -n "Copy ${red}$file${reset} dotfile"
		cp $dotfiles_path$file $dotfiles_dir/
		echo "...done"

		if [ ! -h ~/.$file ]; then
			echo -n "Create symlink .$file"
			ln -s $dotfiles_dir/$file ~/.$file
			echo "...done"
		fi
	done

